import { DataRowsUser } from 'src/@fake-db/types';

export const rows:DataRowsUser[] = [
  {
    id: 1,
    poste: 'Software Developer',
    email: 'john.doe@example.com',
    nom: 'Doe',
    prenom: 'John',
    tele: '1234567890',
    actif: true,
  },
  {
    id: 2,
    poste: 'Data Analyst',
    email: 'jane.smith@example.com',
    nom: 'Smith',
    prenom: 'Jane',
    tele: '0987654321',
    actif: true,
  },
  {
    id: 3,
    poste: 'Project Manager',
    email: 'alex.jones@example.com',
    nom: 'Jones',
    prenom: 'Alex',
    tele: '9876543210',
    actif: true,
  },
  {
    id: 4,
    poste: 'UX/UI Designer',
    email: 'emily.davis@example.com',
    nom: 'Davis',
    prenom: 'Emily',
    tele: '0123456789',
    actif: true,
  },
  {
    id: 5,
    poste: 'System Administrator',
    email: 'michael.brown@example.com',
    nom: 'Brown',
    prenom: 'Michael',
    tele: '5678901234',
    actif: true,
  },
  {
    id: 6,
    poste: 'Network Engineer',
    email: 'sarah.wilson@example.com',
    nom: 'Wilson',
    prenom: 'Sarah',
    tele: '5432109876',
    actif: true,
  },
  {
    id: 7,
    poste: 'Database Administrator',
    email: 'david.wilson@example.com',
    nom: 'Wilson',
    prenom: 'David',
    tele: '6543210987',
    actif: true,
  },
  {
    id: 8,
    poste: 'Business Analyst',
    email: 'olivia.miller@example.com',
    nom: 'Miller',
    prenom: 'Olivia',
    tele: '2345678901',
    actif: true,
  },
  {
    id: 9,
    poste: 'Quality Assurance Engineer',
    email: 'william.taylor@example.com',
    nom: 'Taylor',
    prenom: 'William',
    tele: '8901234567',
    actif: true,
  },
  {
    id: 10,
    poste: 'IT Support Specialist',
    email: 'emma.thomas@example.com',
    nom: 'Thomas',
    prenom: 'Emma',
    tele: '7890123456',
    actif: true,
  },
  {
    id: 11,
    poste: 'Product Manager',
    email: 'lucas.anderson@example.com',
    nom: 'Anderson',
    prenom: 'Lucas',
    tele: '3456789012',
    actif: true,
  },
  {
    id: 12,
    poste: 'Software Engineer',
    email: 'mia.james@example.com',
    nom: 'James',
    prenom: 'Mia',
    tele: '4567890123',
    actif: true,
  }, {
    id: 13,
    poste: 'Network Administrator',
    email: 'noah.roberts@example.com',
    nom: 'Roberts',
    prenom: 'Noah',
    tele: '9012345678',
    actif: true,
  },
  {
    id: 14,
    poste: 'Frontend Developer',
    email: 'mia.johnson@example.com',
    nom: 'Johnson',
    prenom: 'Mia',
    tele: '6789012345',
    actif: true,
  },
  {
    id: 15,
    poste: 'Backend Developer',
    email: 'logan.lewis@example.com',
    nom: 'Lewis',
    prenom: 'Logan',
    tele: '7890123456',
    actif: true,
  },
  {
    id: 16,
    poste: 'System Analyst',
    email: 'amelia.wang@example.com',
    nom: 'Wang',
    prenom: 'Amelia',
    tele: '5678901234',
    actif: true,
  },
  {
    id: 17,
    poste: 'Security Analyst',
    email: 'ethan.brown@example.com',
    nom: 'Brown',
    prenom: 'Ethan',
    tele: '4567890123',
    actif: true,
  },
  {
    id: 18,
    poste: 'DevOps Engineer',
    email: 'ava.martin@example.com',
    nom: 'Martin',
    prenom: 'Ava',
    tele: '3456789012',
    actif: true,
  },{
    id: 19,
    poste: 'UI Designer',
    email: 'oliver.garcia@example.com',
    nom: 'Garcia',
    prenom: 'Oliver',
    tele: '2345678901',
    actif: true,
  },
  {
    id: 20,
    poste: 'Database Developer',
    email: 'ava.robinson@example.com',
    nom: 'Robinson',
    prenom: 'Ava',
    tele: '7890123456',
    actif: true,
  },
  {
    id: 21,
    poste: 'Software Architect',
    email: 'jack.hill@example.com',
    nom: 'Hill',
    prenom: 'Jack',
    tele: '4567890123',
    actif: true,
  },
  {
    id: 22,
    poste: 'IT Consultant',
    email: 'amelia.wright@example.com',
    nom: 'Wright',
    prenom: 'Amelia',
    tele: '9012345678',
    actif: true,
  },
  {
    id: 23,
    poste: 'Business Intelligence Analyst',
    email: 'ethan.ramirez@example.com',
    nom: 'Ramirez',
    prenom: 'Ethan',
    tele: '6789012345',
    actif: true,
  },
  {
    id: 24,
    poste: 'Cloud Engineer',
    email: 'mia.evans@example.com',
    nom: 'Evans',
    prenom: 'Mia',
    tele: '3456789012',
    actif: true,
  },
];
